In [11]:
import pandas as pd
import requests
import os
import time
from dotenv import load_dotenv

load_dotenv("/Users/bytedance/Documents/Mauriciio/Jupyter/Metallica/.env")

LASTFM_API_KEY = os.getenv("LASTFM_API_KEY")
BASE_URL = "http://ws.audioscrobbler.com/2.0/"

big4_tracks = pd.read_csv("big4_studio_tracks_musicbrainz.csv")

big4_tracks.head()

,artist,album_name,first_release_date,release_group_id,release_id,recording_id,track_number,track_position,track_name,track_length_ms
0,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,a620f5e7-ae9d-4089-a947-a1cee4a9435e,A1,1,Hit the Lights,257000.0
1,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,04fc57f2-4dc8-4b84-801b-3699508597e8,A2,2,The Four Horsemen,432706.0
2,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,65ca9607-fa5d-4b5d-b830-3fb168ac9064,A3,3,Motorbreath,188133.0
3,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,321b3122-f443-4709-8098-3afba7cddca9,A4,4,Jump in the Fire,281493.0
4,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,78095e21-30cf-47eb-b367-3af6ee426af5,A5,5,(Anesthesia) Pulling Teeth,254840.0

In [12]:
## Tracks listeners
def get_lastfm_track_info(artist, track):
    params = {
        "method": "track.getInfo",
        "artist": artist,
        "track": track,
        "api_key": LASTFM_API_KEY,
        "format": "json",
        "autocorrect": 1
    }
    
    response = requests.get(BASE_URL, params=params)
    data = response.json()
    
    if "track" not in data:
        return {
            "lastfm_listeners": None,
            "lastfm_playcount": None,
            "lastfm_url": None
        }
    
    track_data = data["track"]
    
    return {
        "lastfm_listeners": int(track_data.get("listeners", 0)),
        "lastfm_playcount": int(track_data.get("playcount", 0)),
        "lastfm_url": track_data.get("url")
    }

In [13]:
lastfm_rows = []

for index, row in big4_tracks.iterrows():
    artist = row["artist"]
    track = row["track_name"]
    
    print(f"{index + 1}/{len(big4_tracks)} - {artist} - {track}")
    
    info = get_lastfm_track_info(artist, track)
    
    lastfm_rows.append({
        "artist": artist,
        "track_name": track,
        **info
    })
    
    time.sleep(0.25)

1/665 - Metallica - Hit the Lights
2/665 - Metallica - The Four Horsemen
3/665 - Metallica - Motorbreath
4/665 - Metallica - Jump in the Fire
5/665 - Metallica - (Anesthesia) Pulling Teeth
6/665 - Metallica - Whiplash
7/665 - Metallica - Phantom Lord
8/665 - Metallica - No Remorse
9/665 - Metallica - Seek & Destroy
10/665 - Metallica - Metal Militia
11/665 - Metallica - Fight Fire With Fire
12/665 - Metallica - Ride the Lightning
13/665 - Metallica - For Whom the Bell Tolls
14/665 - Metallica - Fade to Black
15/665 - Metallica - Trapped Under Ice
16/665 - Metallica - Escape
17/665 - Metallica - Creeping Death
18/665 - Metallica - The Call of Ktulu
19/665 - Metallica - Battery
20/665 - Metallica - Master of Puppets
21/665 - Metallica - The Thing That Should Not Be
22/665 - Metallica - Welcome Home (Sanitarium)
23/665 - Metallica - Disposable Heroes
24/665 - Metallica - Leper Messiah
25/665 - Metallica - Orion
26/665 - Metallica - Damage, Inc.
27/665 - Metallica - Blackened
28/665 - Metallica - …And Justice for All
29/665 - Metallica - Eye of the Beholder
30/665 - Metallica - One
31/665 - Metallica - The Shortest Straw
32/665 - Metallica - Harvester of Sorrow
33/665 - Metallica - The Frayed Ends of Sanity
34/665 - Metallica - To Live Is to Die
35/665 - Metallica - Dyers Eve
36/665 - Metallica - Enter Sandman
37/665 - Metallica - Sad but True
38/665 - Metallica - Holier Than Thou
39/665 - Metallica - The Unforgiven
40/665 - Metallica - Wherever I May Roam
41/665 - Metallica - Don’t Tread on Me
42/665 - Metallica - Through the Never
43/665 - Metallica - Nothing Else Matters
44/665 - Metallica - Of Wolf and Man
45/665 - Metallica - The God That Failed
46/665 - Metallica - My Friend of Misery
47/665 - Metallica - The Struggle Within
48/665 - Metallica - Ain’t My Bitch
49/665 - Metallica - 2 × 4
50/665 - Metallica - The House Jack Built
51/665 - Metallica - Until It Sleeps
52/665 - Metallica - King Nothing
53/665 - Metallica - Hero of the Day
54/665 - Metallica - Bleeding Me
55/665 - Metallica - Cure
56/665 - Metallica - Poor Twisted Me
57/665 - Metallica - Wasting My Hate
58/665 - Metallica - Mama Said
59/665 - Metallica - Thorn Within
60/665 - Metallica - Ronnie
61/665 - Metallica - The Outlaw Torn
62/665 - Metallica - Fuel
63/665 - Metallica - The Memory Remains
64/665 - Metallica - Devil’s Dance
65/665 - Metallica - The Unforgiven II
66/665 - Metallica - Better Than You
67/665 - Metallica - Slither
68/665 - Metallica - Carpe Diem Baby
69/665 - Metallica - Bad Seed
70/665 - Metallica - Where the Wild Things Are
71/665 - Metallica - Prince Charming
72/665 - Metallica - Low Man’s Lyric
73/665 - Metallica - Attitude
74/665 - Metallica - Fixxxer
75/665 - Metallica - Frantic
76/665 - Metallica - St. Anger
77/665 - Metallica - Some Kind of Monster
78/665 - Metallica - Dirty Window
79/665 - Metallica - Invisible Kid
80/665 - Metallica - My World
81/665 - Metallica - Shoot Me Again
82/665 - Metallica - Sweet Amber
83/665 - Metallica - The Unnamed Feeling
84/665 - Metallica - Purify
85/665 - Metallica - All Within My Hands
86/665 - Metallica - Frantic
87/665 - Metallica - St. Anger
88/665 - Metallica - Some Kind of Monster
89/665 - Metallica - Dirty Window
90/665 - Metallica - Invisible Kid
91/665 - Metallica - My World
92/665 - Metallica - Shoot Me Again
93/665 - Metallica - Sweet Amber
94/665 - Metallica - The Unnamed Feeling
95/665 - Metallica - Purify
96/665 - Metallica - All Within My Hands
97/665 - Metallica - That Was Just Your Life
98/665 - Metallica - The End of the Line
99/665 - Metallica - Broken, Beat & Scarred
100/665 - Metallica - The Day That Never Comes
101/665 - Metallica - All Nightmare Long
102/665 - Metallica - Cyanide
103/665 - Metallica - The Unforgiven III
104/665 - Metallica - The Judas Kiss
105/665 - Metallica - Suicide & Redemption
106/665 - Metallica - My Apocalypse
107/665 - Metallica - Brandenburg Gate
108/665 - Metallica - The View
109/665 - Metallica - Pumping Blood
110/665 - Metallica - Mistress Dread
111/665 - Metallica - Iced Honey
112/665 - Metallica - Cheat on Me
113/665 - Metallica - Frustration
114/665 - Metallica - Little Dog
115/665 - Metallica - Dragon
116/665 - Metallica - Junior Dad
117/665 - Metallica - Hardwired
118/665 - Metallica - Atlas, Rise!
119/665 - Metallica - Now That We’re Dead
120/665 - Metallica - Moth Into Flame
121/665 - Metallica - Dream No More
122/665 - Metallica - Halo on Fire
123/665 - Metallica - Confusion
124/665 - Metallica - ManUNkind
125/665 - Metallica - Here Comes Revenge
126/665 - Metallica - Am I Savage?
127/665 - Metallica - Murder One
128/665 - Metallica - Spit Out the Bone
129/665 - Metallica - Lords of Summer
130/665 - Metallica - Ronnie Rising Medley: A Light in the Black / Tarot Woman / Stargazer / Kill the King
131/665 - Metallica - When a Blind Man Cries
132/665 - Metallica - Remember Tomorrow
133/665 - Metallica - Helpless
134/665 - Metallica - Hit the Lights
135/665 - Metallica - The Four Horsemen
136/665 - Metallica - Ride the Lightning
137/665 - Metallica - Fade to Black
138/665 - Metallica - Jump in the Fire
139/665 - Metallica - For Whom the Bell Tolls
140/665 - Metallica - Creeping Death
141/665 - Metallica - Metal Militia
142/665 - Metallica - Hardwired
143/665 - Metallica - 72 Seasons
144/665 - Metallica - Shadows Follow
145/665 - Metallica - Screaming Suicide
146/665 - Metallica - Sleepwalk My Life Away
147/665 - Metallica - You Must Burn!
148/665 - Metallica - Lux Æterna
149/665 - Metallica - Crown of Barbed Wire
150/665 - Metallica - Chasing Light
151/665 - Metallica - If Darkness Had a Son
152/665 - Metallica - Too Far Gone?
153/665 - Metallica - Room of Mirrors
154/665 - Metallica - Inamorata
155/665 - Megadeth - Last Rites / Loved to Deth
156/665 - Megadeth - Killing Is My Business… and Business Is Good!
157/665 - Megadeth - Skull Beneath the Skin
158/665 - Megadeth - These Boots
159/665 - Megadeth - Rattlehead
160/665 - Megadeth - Chosen Ones
161/665 - Megadeth - Looking Down the Cross
162/665 - Megadeth - Mechanix
163/665 - Megadeth - Wake Up Dead
164/665 - Megadeth - The Conjuring
165/665 - Megadeth - Peace Sells
166/665 - Megadeth - Devil’s Island
167/665 - Megadeth - Good Mourning / Black Friday
168/665 - Megadeth - Bad Omen
169/665 - Megadeth - I Ain’t Superstitious
170/665 - Megadeth - My Last Words
171/665 - Megadeth - Into the Lungs of Hell
172/665 - Megadeth - Set the World Afire
173/665 - Megadeth - Anarchy in the U.K.
174/665 - Megadeth - Mary Jane
175/665 - Megadeth - 502
176/665 - Megadeth - In My Darkest Hour
177/665 - Megadeth - Liar
178/665 - Megadeth - Hook in Mouth
179/665 - Megadeth - Holy Wars… The Punishment Due
180/665 - Megadeth - Hangar 18
181/665 - Megadeth - Take No Prisoners
182/665 - Megadeth - Five Magics
183/665 - Megadeth - Poison Was the Cure
184/665 - Megadeth - Lucretia
185/665 - Megadeth - Tornado of Souls
186/665 - Megadeth - Dawn Patrol
187/665 - Megadeth - Rust in Peace… Polaris
188/665 - Megadeth - Skin o’ My Teeth
189/665 - Megadeth - Symphony of Destruction
190/665 - Megadeth - Architecture of Aggression
191/665 - Megadeth - Foreclosure of a Dream
192/665 - Megadeth - Sweating Bullets
193/665 - Megadeth - This Was My Life
194/665 - Megadeth - Countdown to Extinction
195/665 - Megadeth - High Speed Dirt
196/665 - Megadeth - Psychotron
197/665 - Megadeth - Captive Honour
198/665 - Megadeth - Ashes in Your Mouth
199/665 - Megadeth - Reckoning Day
200/665 - Megadeth - Train of Consequences
201/665 - Megadeth - Addicted to Chaos
202/665 - Megadeth - À tout le monde
203/665 - Megadeth - Elysian Fields
204/665 - Megadeth - The Killing Road
205/665 - Megadeth - Blood of Heroes
206/665 - Megadeth - Family Tree
207/665 - Megadeth - Youthanasia
208/665 - Megadeth - I Thought I Knew It All
209/665 - Megadeth - Black Curtains
210/665 - Megadeth - Victory
211/665 - Megadeth - Trust
212/665 - Megadeth - Almost Honest
213/665 - Megadeth - Use the Man
214/665 - Megadeth - Mastermind
215/665 - Megadeth - The Disintegrators
216/665 - Megadeth - I’ll Get Even
217/665 - Megadeth - Sin
218/665 - Megadeth - A Secret Place
219/665 - Megadeth - Have Cool, Will Travel
220/665 - Megadeth - She‐Wolf
221/665 - Megadeth - Vortex
222/665 - Megadeth - FFF
223/665 - Megadeth - One Thing
224/665 - Megadeth - Insomnia
225/665 - Megadeth - Prince of Darkness
226/665 - Megadeth - Enter the Arena
227/665 - Megadeth - Crush ’Em
228/665 - Megadeth - Breadline
229/665 - Megadeth - The Doctor Is Calling
230/665 - Megadeth - I’ll Be There
231/665 - Megadeth - Wanderlust
232/665 - Megadeth - Ecstasy
233/665 - Megadeth - Seven
234/665 - Megadeth - Time: The Beginning
235/665 - Megadeth - Time: The End
236/665 - Megadeth - Duke Nukem Theme
237/665 - Megadeth - Dread and the Fugitive Mind
238/665 - Megadeth - Kill the King
239/665 - Megadeth - Promises
240/665 - Megadeth - The World Needs a Hero
241/665 - Megadeth - Losing My Senses
242/665 - Megadeth - Return to Hangar
243/665 - Megadeth - 1000 Times Goodbye
244/665 - Megadeth - Coming Home
245/665 - Megadeth - Moto Psycho
246/665 - Megadeth - When
247/665 - Megadeth - Capitol Punishment
248/665 - Megadeth - Blackmail the Universe
249/665 - Megadeth - Die Dead Enough
250/665 - Megadeth - Kick the Chair
251/665 - Megadeth - The Scorpion
252/665 - Megadeth - Tears in a Vial
253/665 - Megadeth - I Know Jack
254/665 - Megadeth - Back in the Day
255/665 - Megadeth - Something That I’m Not
256/665 - Megadeth - Truth Be Told
257/665 - Megadeth - Of Mice and Men
258/665 - Megadeth - Shadow of Deth
259/665 - Megadeth - My Kingdom
260/665 - Megadeth - Sleepwalker
261/665 - Megadeth - Washington Is Next!
262/665 - Megadeth - Never Walk Alone… A Call to Arms
263/665 - Megadeth - United Abominations
264/665 - Megadeth - Gears of War
265/665 - Megadeth - Blessed Are the Dead
266/665 - Megadeth - Play for Blood
267/665 - Megadeth - À tout le monde (Set Me Free)
268/665 - Megadeth - Amerikhastan
269/665 - Megadeth - You’re Dead
270/665 - Megadeth - Burnt Ice
271/665 - Megadeth - Out on the Tiles
272/665 - Megadeth - Dialectic Chaos
273/665 - Megadeth - This Day We Fight!
274/665 - Megadeth - 44 Minutes
275/665 - Megadeth - 1,320'
276/665 - Megadeth - Bite the Hand
277/665 - Megadeth - Bodies
278/665 - Megadeth - Endgame
279/665 - Megadeth - The Hardest Part of Letting Go... Sealed With a Kiss
280/665 - Megadeth - Head Crusher
281/665 - Megadeth - How the Story Ends
282/665 - Megadeth - The Right to Go Insane
283/665 - Megadeth - Washington Is Next!
284/665 - Megadeth - Sudden Death
285/665 - Megadeth - Public Enemy No. 1
286/665 - Megadeth - Whose Life (Is It Anyways?)
287/665 - Megadeth - We the People
288/665 - Megadeth - Guns, Drugs, & Money
289/665 - Megadeth - Never Dead
290/665 - Megadeth - New World Order
291/665 - Megadeth - Fast Lane
292/665 - Megadeth - Black Swan
293/665 - Megadeth - Wrecker
294/665 - Megadeth - Millennium of the Blind
295/665 - Megadeth - Deadly Nightshade
296/665 - Megadeth - 13
297/665 - Megadeth - Public Enemy No. 1
298/665 - Megadeth - Kingmaker
299/665 - Megadeth - Super Collider
300/665 - Megadeth - Burn!
301/665 - Megadeth - Built for War
302/665 - Megadeth - Off the Edge
303/665 - Megadeth - Dance in the Rain
304/665 - Megadeth - Beginning of Sorrow
305/665 - Megadeth - The Blackest Crow
306/665 - Megadeth - Forget to Remember
307/665 - Megadeth - Don’t Turn Your Back…
308/665 - Megadeth - Cold Sweat
309/665 - Megadeth - The Threat Is Real
310/665 - Megadeth - Dystopia
311/665 - Megadeth - Fatal Illusion
312/665 - Megadeth - Death From Within
313/665 - Megadeth - Bullet to the Brain
314/665 - Megadeth - Post American World
315/665 - Megadeth - Poisonous Shadows
316/665 - Megadeth - Conquer or Die!
317/665 - Megadeth - Lying in State
318/665 - Megadeth - The Emperor
319/665 - Megadeth - Foreign Policy
320/665 - Megadeth - The Sick, the Dying… and the Dead!
321/665 - Megadeth - Life in Hell
322/665 - Megadeth - Night Stalkers
323/665 - Megadeth - Dogs of Chernobyl
324/665 - Megadeth - Sacrifice
325/665 - Megadeth - Junkie
326/665 - Megadeth - Psychopathy
327/665 - Megadeth - Killing Time
328/665 - Megadeth - Soldier On!
329/665 - Megadeth - Célebutante
330/665 - Megadeth - Mission to Mars
331/665 - Megadeth - We’ll Be Back
332/665 - Megadeth - Tipping Point
333/665 - Megadeth - I Don’t Care
334/665 - Megadeth - Hey, God?!
335/665 - Megadeth - Let There Be Shred
336/665 - Megadeth - Puppet Parade
337/665 - Megadeth - Another Bad Day
338/665 - Megadeth - Made to Kill
339/665 - Megadeth - Obey the Call
340/665 - Megadeth - I Am War
341/665 - Megadeth - The Last Note
342/665 - Megadeth - Ride the Lightning
343/665 - Slayer - Evil Has No Boundaries
344/665 - Slayer - The Antichrist
345/665 - Slayer - Die by the Sword
346/665 - Slayer - Fight Till Death
347/665 - Slayer - Metal Storm / Face the Slayer
348/665 - Slayer - Black Magic
349/665 - Slayer - Tormentor
350/665 - Slayer - The Final Command
351/665 - Slayer - Crionics
352/665 - Slayer - Show No Mercy
353/665 - Slayer - Hell Awaits
354/665 - Slayer - Kill Again
355/665 - Slayer - At Dawn They Sleep
356/665 - Slayer - Praise of Death
357/665 - Slayer - Necrophiliac
358/665 - Slayer - Crypts of Eternity
359/665 - Slayer - Hardening of the Arteries
360/665 - Slayer - Angel of Death
361/665 - Slayer - Piece by Piece
362/665 - Slayer - Necrophobic
363/665 - Slayer - Altar of Sacrifice
364/665 - Slayer - Jesus Saves
365/665 - Slayer - Criminally Insane
366/665 - Slayer - Reborn
367/665 - Slayer - Epidemic
368/665 - Slayer - Postmortem
369/665 - Slayer - Raining Blood
370/665 - Slayer - South of Heaven
371/665 - Slayer - Silent Scream
372/665 - Slayer - Live Undead
373/665 - Slayer - Behind the Crooked Cross
374/665 - Slayer - Mandatory Suicide
375/665 - Slayer - Ghosts of War
376/665 - Slayer - Read Between the Lies
377/665 - Slayer - Cleanse the Soul
378/665 - Slayer - Dissident Aggressor
379/665 - Slayer - Spill the Blood
380/665 - Slayer - War Ensemble
381/665 - Slayer - Blood Red
382/665 - Slayer - Spirit in Black
383/665 - Slayer - Expendable Youth
384/665 - Slayer - Dead Skin Mask
385/665 - Slayer - Hallowed Point
386/665 - Slayer - Skeletons of Society
387/665 - Slayer - Temptation
388/665 - Slayer - Born of Fire
389/665 - Slayer - Seasons in the Abyss
390/665 - Slayer - Killing Fields
391/665 - Slayer - Sex. Murder. Art.
392/665 - Slayer - Fictional Reality
393/665 - Slayer - Dittohead
394/665 - Slayer - Divine Intervention
395/665 - Slayer - Circle of Beliefs
396/665 - Slayer - SS-3
397/665 - Slayer - Serenity in Murder
398/665 - Slayer - 213
399/665 - Slayer - Mind Control
400/665 - Slayer - Disintegration / Free Money
401/665 - Slayer - Verbal Abuse / Leeches
402/665 - Slayer - Abolish Government / Superficial Love
403/665 - Slayer - Can’t Stand You
404/665 - Slayer - Ddamm
405/665 - Slayer - Guilty of Being White
406/665 - Slayer - I Hate You
407/665 - Slayer - Filler / I Don’t Want to Hear It
408/665 - Slayer - Spiritual Law
409/665 - Slayer - Sick Boy
410/665 - Slayer - Mr. Freeze
411/665 - Slayer - Violent Pacification
412/665 - Slayer - Memories of Tomorrow
413/665 - Slayer - Richard Hung Himself
414/665 - Slayer - I’m Gonna Be Your God
415/665 - Slayer - Gemini
416/665 - Slayer - Bitter Peace
417/665 - Slayer - Death’s Head
418/665 - Slayer - Stain of Mind
419/665 - Slayer - Overt Enemy
420/665 - Slayer - Perversions of Pain
421/665 - Slayer - Love to Hate
422/665 - Slayer - Desire
423/665 - Slayer - In the Name of God
424/665 - Slayer - Scrum
425/665 - Slayer - Screaming From the Sky
426/665 - Slayer - Wicked
427/665 - Slayer - Point
428/665 - Slayer - Darkness of Christ
429/665 - Slayer - Disciple
430/665 - Slayer - God Send Death
431/665 - Slayer - New Faith
432/665 - Slayer - Cast Down
433/665 - Slayer - Threshold
434/665 - Slayer - Exile
435/665 - Slayer - Seven Faces
436/665 - Slayer - Bloodline
437/665 - Slayer - Deviance
438/665 - Slayer - War Zone
439/665 - Slayer - Scarstruck
440/665 - Slayer - Here Comes the Pain
441/665 - Slayer - Payback
442/665 - Slayer - Addict
443/665 - Slayer - Flesh Storm
444/665 - Slayer - Catalyst
445/665 - Slayer - Skeleton Christ
446/665 - Slayer - Eyes of the Insane
447/665 - Slayer - Jihad
448/665 - Slayer - Consfearacy
449/665 - Slayer - Catatonic
450/665 - Slayer - Black Serenade
451/665 - Slayer - Cult
452/665 - Slayer - Supremist
453/665 - Slayer - World Painted Blood
454/665 - Slayer - Unit 731
455/665 - Slayer - Snuff
456/665 - Slayer - Beauty Through Order
457/665 - Slayer - Hate Worldwide
458/665 - Slayer - Public Display of Dismemberment
459/665 - Slayer - Human Strain
460/665 - Slayer - Americon
461/665 - Slayer - Psychopathy Red
462/665 - Slayer - Playing With Dolls
463/665 - Slayer - Not of This God
464/665 - Slayer - Psychopathy Red (explicit)
465/665 - Slayer - Delusions of Saviour
466/665 - Slayer - Repentless
467/665 - Slayer - Take Control
468/665 - Slayer - Vices
469/665 - Slayer - Cast the First Stone
470/665 - Slayer - When the Stillness Comes
471/665 - Slayer - Chasing Death
472/665 - Slayer - Implode
473/665 - Slayer - Piano Wire
474/665 - Slayer - Atrocity Vendor
475/665 - Slayer - You Against You
476/665 - Slayer - Pride in Prejudice
477/665 - Slayer - Intro
478/665 - Slayer - Hell Awaits
479/665 - Slayer - The Antichrist
480/665 - Slayer - Mandatory Suicide
481/665 - Slayer - Hate Worldwide
482/665 - Slayer - War Ensemble
483/665 - Slayer - Postmortem
484/665 - Slayer - Captor of Sin
485/665 - Slayer - Disciple
486/665 - Slayer - Seasons in the Abyss
487/665 - Slayer - Born of Fire
488/665 - Slayer - Dead Skin Mask
489/665 - Slayer - Raining Blood
490/665 - Slayer - Black Magic
491/665 - Slayer - South of Heaven
492/665 - Slayer - Angel of Death
493/665 - Slayer - Outro
494/665 - Slayer - Making of Repentless (Documentary)
495/665 - Slayer - Raining Blood
496/665 - Slayer - Angel of Death
497/665 - Slayer - Die by the Sword
498/665 - Slayer - Praise of Death
499/665 - Slayer - Criminally Insane
500/665 - Slayer - Necrophiliac
501/665 - Slayer - Black Magic
502/665 - Slayer - Captor of Sin
503/665 - Slayer - Reborn
504/665 - Slayer - Postmortem
505/665 - Slayer - Epidemic
506/665 - Slayer - Hell Awaits
507/665 - Slayer - Altar of Sacrifice
508/665 - Slayer - Jesus Saves
509/665 - Slayer - At Dawn They Sleep
510/665 - Slayer - Chemical Warfare
511/665 - Anthrax - Deathrider
512/665 - Anthrax - Metal Thrashing Mad
513/665 - Anthrax - I’m Eighteen
514/665 - Anthrax - Panic
515/665 - Anthrax - Subjugator
516/665 - Anthrax - Soldiers of Metal
517/665 - Anthrax - Death From Above
518/665 - Anthrax - Anthrax
519/665 - Anthrax - Across the River
520/665 - Anthrax - Howling Furies
521/665 - Anthrax - A.I.R.
522/665 - Anthrax - Lone Justice
523/665 - Anthrax - Madhouse
524/665 - Anthrax - S.S.C. / Stand or Fall
525/665 - Anthrax - The Enemy
526/665 - Anthrax - Aftershock
527/665 - Anthrax - Armed and Dangerous
528/665 - Anthrax - Medusa
529/665 - Anthrax - Gung‐Ho
530/665 - Anthrax - Among the Living
531/665 - Anthrax - Caught in a Mosh
532/665 - Anthrax - I Am the Law
533/665 - Anthrax - Efilnikufesin (N.F.L.)
534/665 - Anthrax - A Skeleton in the Closet
535/665 - Anthrax - Indians
536/665 - Anthrax - One World
537/665 - Anthrax - A.D.I. / Horror of It All
538/665 - Anthrax - Imitation of Life
539/665 - Anthrax - Be All, End All
540/665 - Anthrax - Out of Sight, Out of Mind
541/665 - Anthrax - Make Me Laugh
542/665 - Anthrax - Antisocial
543/665 - Anthrax - Who Cares Wins
544/665 - Anthrax - Now It’s Dark
545/665 - Anthrax - Schism
546/665 - Anthrax - Misery Loves Company
547/665 - Anthrax - 13
548/665 - Anthrax - Finalé
549/665 - Anthrax - Time
550/665 - Anthrax - Blood
551/665 - Anthrax - Keep It in the Family
552/665 - Anthrax - In My World
553/665 - Anthrax - Gridlock
554/665 - Anthrax - Intro to Reality
555/665 - Anthrax - Belly of the Beast
556/665 - Anthrax - Got the Time
557/665 - Anthrax - H8 Red
558/665 - Anthrax - One Man Stands
559/665 - Anthrax - Discharge
560/665 - Anthrax - Potters Field
561/665 - Anthrax - Only

In [14]:
lastfm_df = pd.DataFrame(lastfm_rows)

big4_enriched = big4_tracks.merge(
    lastfm_df,
    on=["artist", "track_name"],
    how="left"
)

big4_enriched.head()

,artist,album_name,first_release_date,release_group_id,release_id,recording_id,track_number,track_position,track_name,track_length_ms,lastfm_listeners,lastfm_playcount,lastfm_url
0,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,a620f5e7-ae9d-4089-a947-a1cee4a9435e,A1,1,Hit the Lights,257000.0,397876,2596232,https://www.last.fm/music/Metallica/_/Hit+the+...
1,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,a620f5e7-ae9d-4089-a947-a1cee4a9435e,A1,1,Hit the Lights,257000.0,397876,2596232,https://www.last.fm/music/Metallica/_/Hit+the+...
2,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,04fc57f2-4dc8-4b84-801b-3699508597e8,A2,2,The Four Horsemen,432706.0,400450,2786243,https://www.last.fm/music/Metallica/_/The+Four...
3,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,04fc57f2-4dc8-4b84-801b-3699508597e8,A2,2,The Four Horsemen,432706.0,400450,2786243,https://www.last.fm/music/Metallica/_/The+Four...
4,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,65ca9607-fa5d-4b5d-b830-3fb168ac9064,A3,3,Motorbreath,188133.0,394871,2717223,https://www.last.fm/music/Metallica/_/Motorbreath

In [17]:
big4_enriched.duplicated(
    subset=["artist", "album_name", "track_name"]
).sum()

np.int64(161)

In [18]:
dups = big4_enriched[
    big4_enriched.duplicated(
        subset=["artist", "album_name", "track_name"],
        keep=False
    )
]

dups.sort_values(["artist", "album_name", "track_name"])dups[[
    "artist",
    "album_name",
    "track_name",
    "track_length_ms",
    "lastfm_playcount",
    "lastfm_listeners"
]].sort_values(["artist", "album_name", "track_name"])

,artist,album_name,first_release_date,release_group_id,release_id,recording_id,track_number,track_position,track_name,track_length_ms,lastfm_listeners,lastfm_playcount,lastfm_url
648,Anthrax,Among the Living,1987-03-22,413bc69f-9391-3fe3-802b-5bf4922f6066,fbc164e6-c628-4a73-b20d-063c1e335408,0e511421-ee06-47df-ba0d-a58163fdf7a0,1,1,Among the Living,316200.0,222169,1134213,https://www.last.fm/music/Anthrax/_/Among+the+...
649,Anthrax,Among the Living,1987-03-22,413bc69f-9391-3fe3-802b-5bf4922f6066,fbc164e6-c628-4a73-b20d-063c1e335408,0e511421-ee06-47df-ba0d-a58163fdf7a0,1,1,Among the Living,316200.0,222169,1134213,https://www.last.fm/music/Anthrax/_/Among+the+...
650,Anthrax,Among the Living,1987-03-22,413bc69f-9391-3fe3-802b-5bf4922f6066,fbc164e6-c628-4a73-b20d-063c1e335408,732168d4-c45a-4713-b4a5-7049cdb995e6,2,2,Caught in a Mosh,300133.0,339098,2040366,https://www.last.fm/music/Anthrax/_/Caught+in+...
651,Anthrax,Among the Living,1987-03-22,413bc69f-9391-3fe3-802b-5bf4922f6066,fbc164e6-c628-4a73-b20d-063c1e335408,732168d4-c45a-4713-b4a5-7049cdb995e6,2,2,Caught in a Mosh,300133.0,339098,2040366,https://www.last.fm/music/Anthrax/_/Caught+in+...
652,Anthrax,Among the Living,1987-03-22,413bc69f-9391-3fe3-802b-5bf4922f6066,fbc164e6-c628-4a73-b20d-063c1e335408,732168d4-c45a-4713-b4a5-7049cdb995e6,2,2,Caught in a Mosh,300133.0,339098,2040366,https://www.last.fm/music/Anthrax/_/Caught+in+...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,Slayer,South of Heaven,1988-07-05,74292121-e345-3f10-85ae-013f4e5a8cae,90102c45-9bc6-4a6e-9a13-0d0b9c0f877c,95c4a3af-cdc3-4716-9e70-3ec0eff03359,A5,5,Mandatory Suicide,245133.0,288187,1816952,https://www.last.fm/music/Slayer/_/Mandatory+S...
433,Slayer,South of Heaven,1988-07-05,74292121-e345-3f10-85ae-013f4e5a8cae,90102c45-9bc6-4a6e-9a13-0d0b9c0f877c,5659354b-92af-4078-8287-c9ab59501994,A1,1,South of Heaven,298466.0,551169,4105344,https://www.last.fm/music/Slayer/_/South+of+He...
434,Slayer,South of Heaven,1988-07-05,74292121-e345-3f10-85ae-013f4e5a8cae,90102c45-9bc6-4a6e-9a13-0d0b9c0f877c,5659354b-92af-4078-8287-c9ab59501994,A1,1,South of Heaven,298466.0,551169,4105344,https://www.last.fm/music/Slayer/_/South+of+He...
527,Slayer,World Painted Blood,2009-10-28,1722d206-eba4-426e-8977-599057ccdbc8,99241fe7-0e0b-4544-9db4-0071e863d194,6708235b-b4aa-42b7-9b37-47525b04ace9,5,5,Hate Worldwide,172026.0,106944,741155,https://www.last.fm/music/Slayer/_/Hate+Worldwide
528,Slayer,World Painted Blood,2009-10-28,1722d206-eba4-426e-8977-599057ccdbc8,99241fe7-0e0b-4544-9db4-0071e863d194,6708235b-b4aa-42b7-9b37-47525b04ace9,5,5,Hate Worldwide,172026.0,106944,741155,https://www.last.fm/music/Slayer/_/Hate+Worldwide

In [19]:
dups[[
    "artist",
    "album_name",
    "track_name",
    "track_length_ms",
    "lastfm_playcount",
    "lastfm_listeners"
]].sort_values(["artist", "album_name", "track_name"])

,artist,album_name,track_name,track_length_ms,lastfm_playcount,lastfm_listeners
648,Anthrax,Among the Living,Among the Living,316200.0,1134213,222169
649,Anthrax,Among the Living,Among the Living,316200.0,1134213,222169
650,Anthrax,Among the Living,Caught in a Mosh,300133.0,2040366,339098
651,Anthrax,Among the Living,Caught in a Mosh,300133.0,2040366,339098
652,Anthrax,Among the Living,Caught in a Mosh,300133.0,2040366,339098
...,...,...,...,...,...,...
439,Slayer,South of Heaven,Mandatory Suicide,245133.0,1816952,288187
433,Slayer,South of Heaven,South of Heaven,298466.0,4105344,551169
434,Slayer,South of Heaven,South of Heaven,298466.0,4105344,551169
527,Slayer,World Painted Blood,Hate Worldwide,172026.0,741155,106944
528,Slayer,World Painted Blood,Hate Worldwide,172026.0,741155,106944

In [20]:
big4_enriched_clean = big4_enriched.drop_duplicates(
    subset=["artist", "album_name", "track_name"],
    keep="first"
).copy()

In [21]:
print("Before:", big4_enriched.shape)
print("After:", big4_enriched_clean.shape)

big4_enriched_clean.duplicated(
    subset=["artist", "album_name", "track_name"]
).sum()

Before: (813, 13)
After: (652, 13)

np.int64(0)

In [22]:

## Save to csv
big4_enriched_clean.to_csv("big4_tracks_enriched_lastfm.csv", index=False)