In [23]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv("/Users/bytedance/Documents/Mauriciio/Jupyter/Metallica/.env")

LASTFM_API_KEY = os.getenv("LASTFM_API_KEY")

BASE_URL = "http://ws.audioscrobbler.com/2.0/"

artists = ["Metallica", "Megadeth", "Slayer", "Anthrax"]

In [24]:
## Getting popular tracks LAST.FM
all_tracks = []

for artist in artists:
    params = {
        "method": "artist.gettoptracks",
        "artist": artist,
        "api_key": LASTFM_API_KEY,
        "format": "json",
        "limit": 10
    }
    
    response = requests.get(BASE_URL, params=params)
    data = response.json()
    
    tracks = data["toptracks"]["track"]
    
    for rank, track in enumerate(tracks, start=1):
        all_tracks.append({
            "artist": artist,
            "rank": rank,
            "track_name": track["name"],
            "listeners": int(track["listeners"]),
            "playcount": int(track["playcount"]),
            "lastfm_url": track["url"]
        })

top_tracks_df = pd.DataFrame(all_tracks)

top_tracks_df

,artist,rank,track_name,listeners,playcount,lastfm_url
0,Metallica,1,Enter Sandman,1888381,18686946,https://www.last.fm/music/Metallica/_/Enter+Sa...
1,Metallica,2,Nothing Else Matters,1705979,17073053,https://www.last.fm/music/Metallica/_/Nothing+...
2,Metallica,3,Master of Puppets,1650172,16766790,https://www.last.fm/music/Metallica/_/Master+o...
3,Metallica,4,One,1397236,14026914,https://www.last.fm/music/Metallica/_/One
4,Metallica,5,The Unforgiven,1178284,10814541,https://www.last.fm/music/Metallica/_/The+Unfo...
5,Metallica,6,Sad but True,1034844,9030880,https://www.last.fm/music/Metallica/_/Sad+but+...
6,Metallica,7,Fuel,1020088,9031571,https://www.last.fm/music/Metallica/_/Fuel
7,Metallica,8,Battery,915605,7978445,https://www.last.fm/music/Metallica/_/Battery
8,Metallica,9,Whiskey in the Jar,908739,7994202,https://www.last.fm/music/Metallica/_/Whiskey+...
9,Metallica,10,Wherever I May Roam,828139,6542129,https://www.last.fm/music/Metallica/_/Wherever...
10,Megadeth,1,Symphony of Destruction,844332,7269370,https://www.last.fm/music/Megadeth/_/Symphony+...
11,Megadeth,2,Hangar 18,488168,4105757,https://www.last.fm/music/Megadeth/_/Hangar+18
12,Megadeth,3,Tornado of Souls,439226,4069708,https://www.last.fm/music/Megadeth/_/Tornado+o...
13,Megadeth,4,Peace Sells,367986,2903164,https://www.last.fm/music/Megadeth/_/Peace+Sells
14,Megadeth,5,A Tout le Monde,338441,2879388,https://www.last.fm/music/Megadeth/_/A+Tout+le...
15,Megadeth,6,Angry Again,335140,2556345,https://www.last.fm/music/Megadeth/_/Angry+Again
16,Megadeth,7,Take No Prisoners,306072,2222956,https://www.last.fm/music/Megadeth/_/Take+No+P...
17,Megadeth,8,Holy Wars...The Punishment Due,299904,2583536,https://www.last.fm/music/Megadeth/_/Holy+Wars...
18,Megadeth,9,Holy Wars...The Punishment Due - 2004 Remix,285801,2526900,https://www.last.fm/music/Megadeth/_/Holy+Wars...
19,Megadeth,10,In My Darkest Hour,280056,2106997,https://www.last.fm/music/Megadeth/_/In+My+Dar...
20,Slayer,1,Raining Blood,1068760,8805420,https://www.last.fm/music/Slayer/_/Raining+Blood
21,Slayer,2,Angel of Death,814322,6757295,https://www.last.fm/music/Slayer/_/Angel+of+Death
22,Slayer,3,Delusions of Saviour,651999,4181509,https://www.last.fm/music/Slayer/_/Delusions+o...
23,Slayer,4,South of Heaven,551169,4105344,https://www.last.fm/music/Slayer/_/South+of+He...
24,Slayer,5,Piece By Piece,411486,2427472,https://www.last.fm/music/Slayer/_/Piece+By+Piece
25,Slayer,6,Seasons In The Abyss,407988,2964230,https://www.last.fm/music/Slayer/_/Seasons+In+...
26,Slayer,7,Postmortem,401686,2476193,https://www.last.fm/music/Slayer/_/Postmortem
27,Slayer,8,Jesus Saves,379880,2259514,https://www.last.fm/music/Slayer/_/Jesus+Saves
28,Slayer,9,Necrophobic,378440,2216013,https://www.last.fm/music/Slayer/_/Necrophobic
29,Slayer,10,Altar of Sacrifice,370895,2247180,https://www.last.fm/music/Slayer/_/Altar+of+Sa...
30,Anthrax,1,Madhouse,433700,2491832,https://www.last.fm/music/Anthrax/_/Madhouse
31,Anthrax,2,Caught in a Mosh,339098,2040366,https://www.last.fm/music/Anthrax/_/Caught+in+...
32,Anthrax,3,Got the Time,328331,2087719,https://www.last.fm/music/Anthrax/_/Got+the+Time
33,Anthrax,4,Indians,275913,1571803,https://www.last.fm/music/Anthrax/_/Indians
34,Anthrax,5,I Am the Law,248817,1345478,https://www.last.fm/music/Anthrax/_/I+Am+the+Law
35,Anthrax,6,Among the Living,222169,1134213,https://www.last.fm/music/Anthrax/_/Among+the+...
36,Anthrax,7,Antisocial,186586,923188,https://www.last.fm/music/Anthrax/_/Antisocial
37,Anthrax,8,Bring The Noise,186389,848197,https://www.last.fm/music/Anthrax/_/Bring+The+...
38,Anthrax,9,A.I.R.,153019,740059,https://www.last.fm/music/Anthrax/_/A.I.R.
39,Anthrax,10,Metal Thrashing Mad,152301,766673,https://www.last.fm/music/Anthrax/_/Metal+Thra...

In [25]:
## Saving data to csv
top_tracks_df.to_csv("lastfm_top_tracks_big4.csv", index=False)

In [6]:
## Music Brainz
!pip install musicbrainzngs pandas

Collecting musicbrainzngs
  Downloading musicbrainzngs-0.7.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pandas in /Users/bytedance/miniconda3/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading musicbrainzngs-0.7.1-py2.py3-none-any.whl (25 kB)
Installing collected packages: musicbrainzngs
Successfully installed musicbrainzngs-0.7.1

In [26]:
## Connect to MB
import musicbrainzngs
import pandas as pd
import time

musicbrainzngs.set_useragent(
    "BigFourThrashDashboard",
    "0.1",
    "macob39@gmail.com"
)

In [27]:
## Getting big four data
artists = ["Metallica", "Megadeth", "Slayer", "Anthrax"]

all_albums_list = []
all_tracks_list = []

for artist_name in artists:
    print(f"Processing {artist_name}...")
    
    artist_id, clean_artist_name = get_artist_id(artist_name)
    
    albums_df = get_studio_release_groups(artist_id, clean_artist_name)
    
    track_rows = []
    
    for _, album in albums_df.iterrows():
        tracks = get_tracks_from_release_group(album["release_group_id"])
        
        for track in tracks:
            track_rows.append({
                "artist": album["artist"],
                "album_name": album["album_name"],
                "first_release_date": album["first_release_date"],
                "release_group_id": album["release_group_id"],
                **track
            })
    
    tracks_df = pd.DataFrame(track_rows)
    
    safe_name = artist_name.lower().replace(" ", "_")
    
    albums_df.to_csv(f"{safe_name}_studio_albums_musicbrainz.csv", index=False)
    tracks_df.to_csv(f"{safe_name}_studio_tracks_musicbrainz.csv", index=False)
    
    all_albums_list.append(albums_df)
    all_tracks_list.append(tracks_df)

print("Done!")

Processing Metallica...
Processing Megadeth...
Processing Slayer...
Processing Anthrax...
Done!

In [28]:
## Join data
big4_albums = pd.concat(all_albums_list, ignore_index=True)
big4_tracks = pd.concat(all_tracks_list, ignore_index=True)

big4_albums.to_csv("big4_studio_albums_musicbrainz.csv", index=False)
big4_tracks.to_csv("big4_studio_tracks_musicbrainz.csv", index=False)

big4_tracks.head()

,artist,album_name,first_release_date,release_group_id,release_id,recording_id,track_number,track_position,track_name,track_length_ms
0,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,a620f5e7-ae9d-4089-a947-a1cee4a9435e,A1,1,Hit the Lights,257000
1,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,04fc57f2-4dc8-4b84-801b-3699508597e8,A2,2,The Four Horsemen,432706
2,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,65ca9607-fa5d-4b5d-b830-3fb168ac9064,A3,3,Motorbreath,188133
3,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,321b3122-f443-4709-8098-3afba7cddca9,A4,4,Jump in the Fire,281493
4,Metallica,Kill ’Em All,1983-07-25,f44f4f73-a714-31a1-a4b8-bfcaaf311f50,a89e1d92-5381-4dab-ba51-733137d0e431,78095e21-30cf-47eb-b367-3af6ee426af5,A5,5,(Anesthesia) Pulling Teeth,254840

In [29]:
big4_albums.groupby("artist")["album_name"].nunique()
big4_tracks.groupby("artist")["track_name"].count()

artist
Anthrax      155
Megadeth     188
Metallica    154
Slayer       168
Name: track_name, dtype: int64